resource_types:
# https://github.com/linkyard/concourse-helm-resource
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
# https://github.com/cloudfoundry-community/slack-notification-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
# https://github.com/jtarchie/github-pullrequest-resource
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources: 
  - name: PolicyValidationAPI
    type: git 
    source: 
      uri: https://github.com/AmitKrVarman/PolicyValidationAPI
  - name: PolicyValidationAPI-docker-image
    type: docker-image
    source:
      email: {{docker-email}}
      username: {{docker-username}}
      password: {{docker-password}}
      repository: {{docker-image}}
  - name: slack-notification
    type: slack-notification
    source:
      url: {{slack-url}}
  

jobs: 
  - name: build-docker-image
    public: true
    serial: true
    plan: 
    - get: PolicyValidationAPI
      trigger: true
    - put: PolicyValidationAPI-docker-image
      params: 
        build: PolicyValidationAPI
    - put: slack-notification
      params:
        # channel: '#infrastructure'
        # text_file: results/message.txt
        text: |
          The build had a result. Check it out at:
          https://concourse.{{domain}}/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.{{domain}}/builds/$BUILD_ID

          Result: Successfully pushed new docker image   
  - name: build-helm-chart
    public: true
    plan: 
    - get: PolicyValidationAPI
    - task: lint-helm
      file: PolicyValidationAPI/ci/lint_helm.yaml
    - put: slack-notification
      params:
        # channel: '#infrastructure'
        # text_file: results/message.txt
        text: |
          The build had a result. Check it out at:
          https://concourse.{{domain}}/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.{{domain}}/builds/$BUILD_ID

          Result: Successfully built new Helm Chart   
